### ISSUE TITLE
`\foreach` example missing a xtick?

### ISSUE THREAD

**Issue by titanic-jb** [pgf-tikz/pgf#1019]
Version: 3.1.9a

I think, the `\foreach` of Karls tutorial example on page 44 has a typo.  

The example reads
``` tex
 \foreach \x in {-1cm,-0.5cm,1cm}
    \draw (\x,-1pt) -- (\x,1pt);
```
which is syntactically correct, but due to the clipping command in effect, none of the defined ticks on the x-axis is visible.  (The only xtick visible in the given clip would be on x = 1cm, but in that area, it will be hidden "within" the line of the circle.)

The following `\foreach` command for the ticks on the y-axis has four elements:
``` tex
\foreach \y in {-1cm,-0.5cm,0.5cm,1cm}
    \draw (-1pt,\y) -- (1pt,\y);
```
resulting in a visible tick at y = .5cm.

I consider this a bug or typo.  If you agree, it could be fixed with this code:
``` tex
\begin{tikzpicture}[scale=3]
\clip (-0.1,-0.2) rectangle (1.1,1.51); \draw[step=.5cm,gray,very thin] (-1.4,-1.4) grid (1.4,1.4); \filldraw[fill=green!20,draw=green!50!black] (0,0) -- (3mm,0mm)
arc [start angle=0, end angle=30, radius=3mm] -- cycle; \draw[->] (-1.5,0) -- (1.5,0);
\draw[->] (0,-1.5) -- (0,1.5);
\draw (0,0) circle [radius=1cm];
  \foreach \x in {-1cm,-0.5cm,0.5cm,1cm}
    \draw (\x,-1pt) -- (\x,1pt);
  \foreach \y in {-1cm,-0.5cm,0.5cm,1cm}
    \draw (-1pt,\y) -- (1pt,\y);
\end{tikzpicture}
```

If you wrote the example code by intention, close this issue.

**Comment by muzimuzhi** [comment]
I guess the missing tick at `x = 0.5cm` is to avoid cross with the thick blue line representing `cos \alpha`, although the latter line is not drawn in `\foreach` examples. Also note the `\clip` in these examples are used to save some space and put emphasis on what is added/changed in current step. Perhaps the manual could add a line to remind users that they can comment the `\clip` when running examples for learning.

**Comment by titanic-jb** [comment]
At least, that xtick is missing in following examples, so I think, it was left by purpose and intention.

**Comment by titanic-jb** [comment]
Maybe a note in the text near that example could clarify it for the user, that this tic was left intentionally?

**Comment by 3geek14** [comment]
Page 31 begins the tutorial with the full desired diagram. I believe the lack of a tick at x=0.5 is to avoid overlapping with `\cos\alpha`, as muzimuzhi said. I think the omission is intentional, so I don't think it should be put in. However, I think the clip could be adjusted to better show the ticks being added, rather than just showing a single one.

    \clip (-0.1,-0.2) rectangle (1.1,1.51);

could be replaced by

    \clip (-0.6,-0.6) rectangle (0.6,1.1);

Of the 7 ticks, 4 are hard to see under the circle. This would make the other 3 easily visible, and one of the remaining 3 (the top one) would still be in frame. This is almost the same size as the current clip, but it's 0.01 shorter in the y-direction. I assume that's not going to impact much regarding where things are, but it's possible.
