### ISSUE TITLE
Fadings do not work and result in error message when externalize is enabled

### ISSUE THREAD

**Issue by aterenin** [pgf-tikz/pgf#1044]
**Brief outline of the bug**

The `tikzfadingfrompicture` environment does not work `\tikzexternalize`, and results in an error even if the fading is correct and copy/pasted from TikZ manual.

**Minimal working example (MWE)**

```
\documentclass[11pt]{book}

\usepackage{pgfplots}
\usepgfplotslibrary{external}
\usetikzlibrary{fadings}

\tikzexternalize

\begin{document}

test

\begin{tikzfadingfrompicture}[name=fade right with circle]
    \fill[transparent!50] (1,1) circle (0.7);
\end{tikzfadingfrompicture}

test

\end{document}
```

Error: `\begin{tikzfadingfrompicture} on input line 13 ended by \end{document}.`

Tested on pdflatex with TeX Live 2021. Error goes away if `tikzfadingfrompicture` is wrapped in `\tikzexternaldisable` and `\tikzexternalenable` but I'm not sure if this causes other problems.

**Comment by muzimuzhi** [comment]
Since the `tikzfadingframpicture` env uses `\tikzpicture` and `\endtikzpicture` internally, some compatibility code is needed in `external` lib. That code was added to `\tikzexternal(disable|enable)` in https://github.com/pgf-tikz/pgf/commit/85fc557e76c9ba802717c7f407f9a58c0ece7a26, but the `\tikzexternalize` seems to be forgotten.

**Comment by muzimuzhi** [comment]
> That code was added to `\tikzexternal(disable|enable)` in [85fc557](https://github.com/pgf-tikz/pgf/commit/85fc557e76c9ba802717c7f407f9a58c0ece7a26), but the `\tikzexternalize` seems to be forgotten.

I was wrong. [`\tikzexternalize` calls `\tikzexternalenable`](https://github.com/pgf-tikz/pgf/blob/85d2c38b78407e5b1ba42140dfd11fcdf8df1edf/tex/generic/pgf/frontendlayer/tikz/libraries/tikzexternalshared.code.tex#L381), so it's the compatibility code that is problematic.

The problem here is, after `\end{tikzfadingfrompicture}`, `\@currenvir` is not restored to `document`. Then `\end{document}` thinks it's closing a `tikzfadingfrompicture` env, so raises the error.
