### ISSUE TITLE
Opacity/transparency not working with TeXLive 2021 XeTeX

### ISSUE THREAD

**Issue by Ionic** [pgf-tikz/pgf#1078]
Setting an opacity via `pgfsetfillopacity` does not seem to have any effect with TeXLive 2021's XeTeX.

The MWE works fine with `luatex`, though.

**Minimal working example (MWE)**

```latex
\documentclass{article}
\usepackage{fontspec}
\usepackage{pgf}

\begin{document}

\fontsize{48}{48}\selectfont
\fontspec{Arial}
{%
\pgfsetfillopacity{0.5}
{\color{red}X}\kern-1ex
{\color{green}Y}\kern-0.8ex
{\color{blue}Z}\kern-0.8ex
}

Dummy text.


\end{document}
```

XeTeX: ![image](https://user-images.githubusercontent.com/1229578/143810517-56af714c-2a40-4c17-8b19-7ed7a005fb6d.png)
luatex: ![image](https://user-images.githubusercontent.com/1229578/143810538-bba3a70f-65b4-456f-ba55-0c7b0b092331.png)

**Comment by Ionic** [comment]
I originally noticed that with `beamer` and submitted josephwright/beamer#738, but it seems to be a general issue that `beamer` merely stumbled upon.

**Comment by samcarter** [comment]
... looking at the .log file, this is probably due to an old xelatex version

**Comment by muzimuzhi** [comment]
According to the uploaded [presentation.log](https://github.com/josephwright/beamer/files/7617077/presentation.log) in https://github.com/josephwright/beamer/issues/738#issuecomment-981442982, 

> ```
> This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021 Gentoo Linux) (preloaded format=xelatex 2021.11.29)  29 NOV 2021 10:22
> [...]
> (/usr/share/texmf-dist/tex/latex/graphics-def/xetex.def
> File: xetex.def 2020/08/26 v5.0i Graphics/color driver for xetex
> ))
> ```

you're using a latest xelatex but with outdated `xetex.def`. Since your example works well in all of my local latest texlive 2021, overleaf's texlive 2021 and 2020, I'm closing this.

btw: To use `\pgfsetfillopacity{0.5}` outside of `pgfpicture` environment and restrict it's scope in xetex, you may want something equivalent to `\special{pdf:code q} \pgfsetfillopacity{0.5} ... \special{pdf:code Q}`.

**Comment by Ionic** [comment]
I'll add this to my MWE, just for good measure.

Thank you. It looks like nobody can reproduce this, unless using Gentoo, so it must be a distro-specific bug. I've asked around and other Gentoo users can reproduce the issue. I'll forward the bug report to them to figure out.

**Comment by samcarter** [comment]
@Ionic ... that's not distro-specific, just specific to the snapshot of texlive you are using.
