### ISSUE TITLE
MWE for using the system layer directly

### ISSUE THREAD

**Issue by tpapp** [pgf-tikz/pgf#1223]
I am experimenting with generating plots using Julia, and using pgf as a drawing backend for primitives like lines etc.

But there must be something I am missing, because when I read try to compile
```latex
\documentclass{minimal}
\def\pgfsysdriver{pgfsys-pdftex.def}
\usepackage{pgfsys}
\begin{document}
\pgfsys@beginpicture
\pgfsys@moveto{0pt}{0pt}
\pgfsys@lineto{10pt}{10pt}
\pgfsys@stroke
\pgfsys@endpicture
\end{document}
```
I get a long list of errors, starting with a `Missing \begin{document}.`.

An MWE for the using the system layer directly from LaTeX would help me a lot.

**Comment by hmenke** [comment]
`\makeatletter` et cetera?

Why do you want to use the system layer? You will have to reimplement all the protocols for syncing paths and boxes. Better use the basic later which also has a public API (i.e. commands without `@` in their names).

**Comment by tpapp** [comment]
Thanks. This works, except for the bounding box:
```latex
\documentclass[tikz]{standalone}
\usepackage{pgfcore}
\begin{document}
\begin{standalone}
  \begin{pgfpicture}
    \makeatletter
    \pgfsys@beginpicture
    \pgfsys@moveto{0pt}{0pt}
    \pgfsys@lineto{10cm}{-10cm}
    \pgfsys@stroke
    \pgfsys@endpicture
    \makeatother
  \end{pgfpicture}
\end{standalone}
\end{document}
```

My expectation is that using the system layer directly will be faster. But I have not (yet) benchmarked this on a larger figure.

**Comment by hmenke** [comment]
> This works, except for the bounding box:

As I said, when using the system layer you will have to reimplement all the protocols.

> My expectation is that using the system layer directly will be faster.

I doubt that it will be measurably faster. The main bottleneck in PGF is loading the package. There are some expansion-heavy operations in pgfmath and of course in TikZ, but if you feed precomputed values from Julia, you should be able to sidestep most of the pgfmath expansions.

**Comment by tpapp** [comment]
Thanks for the explanation.

Which operations are expensive exactly? Eg if I use `\pgfpoint{}{}`, what units should I use? Or anything goes as long as I am using concrete units (`cm`, `pt`, ...), and not operations like `+`?

**Comment by muzimuzhi** [comment]
@tpapp `\pgfqpoint{<x>}{<y>}` is always quicker than `\pgfpoint` (`q` stands for quick) since the former does direct dimension assignments hence involves no `\pgfmathparse`.

Constraint: `<x>` and `<y>` must be dimensions like `1pt`, `2.5cm` (I think all units works as fast as each other) or simple dimension expressions that `\dimexpr` supports, like `\dimexpr 1pt + 2.5cm`.

Slightly slower is `\pgfpoint{+<x>}{+<y>}`. `\pgfmathparse` is involved but quickly returns due to the special prefix `+`. Same constraint to `<x>` and `<y>`.

**Comment by tpapp** [comment]
Thanks. What's the internal unit that `pgf` uses? I might as well just use that with `\pgfqpoint`. Is it `bp`?

**Comment by ilayn** [comment]
With TeX you don't need to bother with performance if Julia is on the other side because it will be always donkey speed vs. a hypercar. A fast or a slow donkey wouldn't matter much. I would in fact use `pgfplots `and develop different plot types there so that you don't reinvent `pgfplots`. Another issue you will encounter is the data amount for plots because TeX will choke up very quickly if you supply too many points for any plots (say more than a few thousand points).

Not to discourage you, I did the same using Python and the sweet spot is to find a way to downsample data so that `pgfplots `can handle it and let `pgfplots `do the PDF arrangements while you focus on the plotting capabilities. You can also consider https://github.com/cjdoris/Bokeh.jl or similar attempts to use modern tools instead of using TeX.

**Comment by tpapp** [comment]
@ilayn:

>  A fast or a slow donkey wouldn't matter much.

Sorry, I don't get this. If `pgf` is the bottleneck, then it makes sense to optimize it if possible.

> so that you don't reinvent pgfplots.

I am one of the maintainers of [PGFPlotsX.jl](https://github.com/KristofferC/PGFPlotsX.jl), so I am aware of its advantages and disadvantages. This is just an experiment. That said,

> TeX will choke up very quickly if you supply too many points for any plots (say more than a few thousand points).

I find this is mitigated a lot by using LUALaTeX. YMMV.

**Comment by hmenke** [comment]
I think at this point the main question should have been answered. The issue tracker is not suited for extended discussion. Please continue your discussion on the mailing list https://tug.org/mailman/listinfo/pgf-tikz, in the Matrix chat [#pgf-tikz:matrix.org](https://matrix.to/#/#pgf-tikz:matrix.org), or in the community forums (e.g. https://tex.stackexchange.com/).
