### ISSUE TITLE
Provide documentation suitable for printing

### ISSUE THREAD

**Issue by SwitWu** [pgf-tikz/pgf#1246]
### Brief outline of the proposed feature

I think it will be helpful if a print version documentation is provided at the same time. I mean using black or dark colors as much as possible and a larger font size (11pt perhaps) in the documentation.

**Comment by hmenke** [comment]
Use Ghostscript
```
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sColorConversionStrategy=Gray -dProcessColorModel=/DeviceGray -sOutputFile=pgfmanual-gray.pdf pgfmanual.pdf
```
Not sure whether shadings and transparency groups will survive this conversion.

**Comment by SwitWu** [comment]
![1](https://user-images.githubusercontent.com/39337667/226187586-ddb9e63d-2afe-4a9a-aa15-0cac1fa81ec6.png)

I used the command line method given above.

The circled parts may not have good printing effect since they are not really "dark".
And setting the font size option to the `\documentclass` seems to be the unique way to change the font size?

**Comment by muzimuzhi** [comment]
@SwitWu It seems the colors used  in `codeexample`s (the highlighted code at lower part of your screenshot) are set by
https://github.com/pgf-tikz/pgf/blob/584b5ffb88e577b567ad8653854965fe3a5be3bd/tex/latex/pgf/doc/pgfmanual-en-macros.tex#L1876-L1902
But there are other color settings scattered all over the place.

The upper right part of your screenshot is another case, in which direct color (or color expressions) are used:
https://github.com/pgf-tikz/pgf/blob/584b5ffb88e577b567ad8653854965fe3a5be3bd/doc/generic/pgf/pgfmanual-en-main-body.tex#L357-L362
Here you cannot simply redefine base colors `red` and `blue`, because their original definitions are used in and expected by `tikzpicture`s.

Also changing font size may interact with all the manually inserted line and page breaks.  To handle all these cases, quite some efforts are required.
