### ISSUE TITLE
Length, surface, angle between

### ISSUE THREAD

**Issue by juanfal** [pgf-tikz/pgf#1247]
### Brief outline of the proposed feature

After many hours using this amazing package, I can't help but to beg for the basic query operator:

    \length {number} (A) -- (B); % would give \lengthnumber macro with the distance between (A) and (B) or larger paths lengths
    \angle {number} (A) -- (B) (C)--(D); % would give \anglenumber macro with the angle between (A)-(B) and (C)-(D)
    \suface {number} (A) -- (B)… --cycle; % would give \surfacenumber macro with the surface of that closed surface

Those are basic operators, pretty difficult and embarrassing to build with pgf and far from reach from any not advanced user.

PD.: I have only imagined a syntax for them, based on other objects syntax, but I am aware it could be totally different

**Comment by hmenke** [comment]
1. Length is probably quite trivial to do. There is already `\pgfdecoratyedpathlength` inside decorations, which could be reused.
2. This requires both path to be straight lines which is not entirely trivial to assert. Also there is an ambiguity with respect to the sign of the angle that the user might expect.
3. Highly non-trivial. Think of self-intersecting paths.

**Comment by juanfal** [comment]
Thanks @hmenke, I don't see why for the `\angle` is necessary to ensure `(A) -- (B) (C) -- (D)` be straight lines… aren't they coordinates connecting straight lines?
You are absolutely right with respect to the `\surface` and, by the way, is the lest important in the general case.  Lengh and angle are really useful, always

**Comment by hmenke** [comment]
So you're only ever dealing with straight lines that have a single segment? In this case what you request is already there with very minimal effort using the `let` operation:

```tex
% \usetikzlibrary{calc}
\path let
  \p1 = ($(B)-(A)$),
  \n{length} = {veclen(\x1,\y1)}
in
  node {\n{length}};
  
\path let
  \p1 = ($(B)-(A)$),
  \p2 = ($(D)-(C)$),
  \n{angle} = {acos((\x1*\x2+\y1*\y2)/(veclen(\x1,\y1)*veclen(\x2,\y2))}
in
  node {\n{angle}};
```

**Comment by ilayn** [comment]
Also

![image](https://user-images.githubusercontent.com/1303842/227743671-3e939dd2-cecc-4e71-a79e-87c34dbdbf52.png)

**Comment by juanfal** [comment]
Well, that's the problem!  `let` is totally local, quite complicate for it to take distances in a complex figure in which you have different parts and need to know 'globally' the distance between typical TikZ coordinates.  On the other hand just the very fact of getting the `x` and `y` coordinates of a `(Coordinate)` is quite cumbersome, impossible for a non-advanced user.  _ChatGPT_ told me after days of desperate search, you had to use `(A.x)` and `(A.y)`.  What a joke!

The use of `let` is then, not only complicate but impossible for among-paths use of distances.
The computation of angles using that 95.5 formula (I didn't know it, I have to confess), is out of the game, as it uses again the `x` and `y` coordinates of `(Coordinates)`, again really obscure to tell.

The idea is having length and angle as _first-class citizen_ as they are so necessary for many pictures…

**Comment by juanfal** [comment]
> So you're only ever dealing with straight lines that have a single segment? In this case what you request is already there with very minimal effort using the `let` operation:
> 
> ```
> % \usetikzlibrary{calc}
> \path let
>   \p1 = ($(B)-(A)$),
>   \n{length} = {veclen(\x1,\y1)}
> in
>   node {\n{length}};
>   
> \path let
>   \p1 = ($(B)-(A)$),
>   \p2 = ($(D)-(C)$),
>   \n{angle} = {acos((\x1*\x2+\y1*\y2)/(veclen(\x1,\y1)*veclen(\x2,\y2))}
> in
>   node {\n{angle}};
> ```

But, can I take those figures outside of those paths for them to be used in another path/place? I think it is impossible, at the normal user level.

**Comment by ilayn** [comment]
> On the other hand just the very fact of getting the x and y coordinates of a (Coordinate) is quite cumbersome, impossible for a non-advanced user. ChatGPT told me after days of desperate search, you had to use (A.x) and (A.y). What a joke!

What are you talking about here? TeX Stackexchange is full of these questions, I answered at least 10 questions about this when I was active there. You need to improve your search-fu. 

Your syntax is exactly what TikZ is running away from. A distance calculation is a math function so inside the **draw**ing operation you have to do something to stop the parsing. What is so obscure in the following code?

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{calc}
\begin{document}
\begin{tikzpicture}
  \draw [help lines] (0,0) grid (3,2);
  \node (A) {A};
  \node (B) at (1,2) {B};
  \path 
  let
    \p1 = ($(B)-(A)$), \n1 = {veclen(\x1,\y1)}
  in 
    \pgfextra{
      \xdef\myvar{\n1} % Save for later use if you want to make things survive after this scope
    }
;
\draw (0,0) circle [radius=\myvar];  % Using my var that survived here
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/1303842/227760792-1960609d-094f-4c1b-b775-110d2c5a3a6d.png)


Other options are tikzmath library which does exactly this or calc or pure PGF. You cannot escape from TeX while using TeX. If you want even more convenient code syntax then define this into a `/.style` or your own function or whatever. 

> But, can I take those figures outside of those paths for them to be used in another path/place? I think it is impossible, at the normal user level.

Of course it is, but you have claims before you have the necessary TikZ skills. Hence every slightly confusing command is driving you to the same "this is terrible" conclusion. Try to go through similar questions on TeX.SX and things will get much easier.

**Comment by muzimuzhi** [comment]
`tkz-euclide`, a package based on `tikz`, provides
- `\tkzCalcLength(A,B) \tkzGetLength{dAB}` to store the length of segment AB in `\dAB`, in cm and
- `\tkzFindAngle(A,B,C) \tkzGetAngle{angleABC}` to store the value of angle ABC in `\angleABC`, in degree and in range `(0, 360]`.
<details><summary>An example</summary>
<p>

```tex
\documentclass{article}
\usepackage{tkz-euclide}
\usetikzlibrary{angles, calc}

\begin{document}
\begin{tikzpicture}
  \path[rotate=30]
    coordinate (A) at (0, 0)
    coordinate (B) at (4, 0)
    coordinate (C) at (0, 3);
  \draw (A) node[below] {A} -- (B) node[right] {B} -- (C) node[left] {C} -- cycle
    pic[draw] {right angle=B--A--C};

  \tkzCalcLength(A,B) \tkzGetLength{dAB}
  \tkzFindAngle(C,B,A) \tkzGetAngle{angleCBA}
  \tkzFindAngle(A,C,B) \tkzGetAngle{angleACB}

  \node[align=left, anchor=south west] at (2.5, 0) {
    $\overline{AB} = \dAB \,\textrm{cm}$ \\
    $\angle CBA + \angle ACB = \ExpandArgs{e}\fpeval{round(\angleCBA+\angleACB,2)}^\circ$ \\
  };
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/227779504-72c66ed0-0451-4787-b86e-fdc90a0f9b25.png)

</p>
</details>

See more info in package doc for `tkz-euclide` v5.02c, sec. 36.2 and 19.2--19.3.

**Comment by juanfal** [comment]
> Of course it is, but you have claims before you have the necessary TikZ skills. Hence every slightly confusing command is driving you to the same "this is terrible" conclusion. Try to go through similar questions on TeX.SX and things will get much easier.

Thanks, those are good ideas, I didn't dig at the level of PGF commands, except for the basic tikzmath… asignation of values and basic computations.  I still think, not having those **basic** commands is a pity in this amazing package, as @muzimuzhi  says, tkz-euclide has it in a naturally way as anybody would expect length should be there

On the other hand, I have to thank you @ilayn for your time and patience, but think that if you have needed to answer this question such amount of times, is because everybody has the same problem.

Thanks a lot!

**Comment by ilayn** [comment]
No problem at all, my pleasure. What I have to mention is the following for a bigger picture. TikZ front end is designed to run away from TeX macros and hide that horrific syntax inside key/value settings. This is partly because they are way easier to handle and abstracts things nicely, and more importantly writing and maintaining fully expandable macros is a major pain in the ass in TeX. That's why things get written into `\pgfmathresult` or `\tkzCalcLength` stores into `\tkzGetLength{dAB}`. 

So typically this is done in `let in` for local operations. If you have bigger plans for dealing with different nodes then you get that operation locally leading to multiple times writing the same stuff. So you have to make a choice either step up your PGF-fu and start writing a bit more sophisticated code which is really not that hard. 

Here is one example that I'm hoping that I'm not committing any crimes since my TeX skills decayed rapidly in the last years. 

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{calc}
\makeatletter
\tikzset{store length of/.code args={#1,#2->#3}{%
\begingroup%  Be respectful for the previous calculations that might have happened
  \pgfpointdiff{\pgfpointanchor{#1}{center}}{\pgfpointanchor{#2}{center}}%  Get center anchor difference of two inputs
  \pgfmathveclen{\pgf@x}{\pgf@y}%  Measure distance
  \pgfmathparse{\pgfmathresult/28.45274}%  Convert pt to cm
  \expandafter\xdef\csname#3\endcsname{\pgfmathresult}%  TeX stuff for global assignment
  \endgroup%
  }
}
\makeatother
\begin{document}
\begin{tikzpicture}
  \draw [help lines] (0,0) grid (3,2);
  \node (A) at (2,1){A};
  \node (B) at (1,2) {B};

\draw[store length of={A,B->myvar}] (A.center) --++ (135:\myvar);
\node {\myvar};
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/1303842/227806248-d4221e52-cc20-4cea-8698-eaa0d3def2d9.png)


The purpose of this example is to show how to cook up your own machinery, *still using the front-end*, and deploy it as a style. Note that, these calculations are very shaky when scalings are involved and TeX is practically a terrible language with its stupid fixed-point arithmetic and many other quirks (I'm exaggerating, it's just too old, but people don't stop using it). Hence there is a reason why you don't do integrals etc. PSTricks however can smoke all this while asleep but it has even worse user API hence the reason why you have partial support for one thing and full support for another.

**Comment by juanfal** [comment]
I'll use this incredible macro (?)!  Thanks!!

I'm used to standard languages.  I have programmed and taught dozens of languages (from assembly to ruby), but I now see you a wizard.  I hope to command this very low level/very high level pgf-tikz environment, as I am enjoying it a lot. Using SublimeText and Skim, and having the editor next to the output, and parametrising the pictures making them dependant on angles and lengths is so funny!  Thanks

**Comment by ilayn** [comment]
> I'm used to standard languages. I have programmed and taught dozens of languages (from assembly to ruby), but I now see you a wizard

Haha I wish. It's more like a cobol programming. If banks should have switched to something else we wouldn't be doing this :) I just read the source code more than I would have liked during my studies. For example now I see that I used `,` to separate arguments in the custom arg expression because I am stupid and forgot that TikZ uses it to separate key expressions. That's probably why I used a brace pair around the argument. Also `store length of` is not a good naming choice now that I think of it.

But anyways I hope I got the point across that typical TikZ customization is to set some key or "style" so that ugly stuff stays hidden from the API. Once you get the hang of what PGF does underneath then it is indeed a breeze. 

> parametrising the pictures making them dependant on angles and lengths is so funny!

Oh then you would enjoy https://github.com/fhackenberger/ktikz I'll close this if you don't mind but feel free to continue the discussion if we can be of further assistance.
