### ISSUE TITLE
Beamer footers disappear when using TikZ with image overlay

### ISSUE THREAD

**Issue by christopherbabcock** [pgf-tikz/pgf#1366]
### Brief outline of the bug

When overlapping/overlaying images in a Beamer presentation, the footer generally disappears without much work around. I have included two slides below. The first frame does not display the footer. After the pause and second image displays, the footer appears. The second frame shows a work around with more items hard coded to force the footer to display with the first image but requires manual manipulation and placing of the image anchoring. Can TikZ operate correctly with footers displaying?

### Minimal working example (MWE)

\documentclass[
	11pt]{beamer}

\graphicspath{{img/}} % Specifies where to look for included images (trailing slash required)
\usepackage{booktabs} % Allows the use of \toprule, \midrule and \bottomrule for better rules in tables
\usepackage{graphicx} % Allows including images
\usepackage{multirow}
\usepackage{array}
\usepackage{bookmark}
\usepackage{amssymb}
\usepackage{tikz}
\usepackage{cancel}
\usepackage{physics}
\usepackage{amsmath}

%----------------------------------------------------------------------------------------
%	SELECT LAYOUT THEME
%----------------------------------------------------------------------------------------
\usetheme{Boadilla}

%----------------------------------------------------------------------------------------
%	SELECT FONT THEME & FONTS
%----------------------------------------------------------------------------------------
\usefonttheme{default} % Typeset using the default sans serif font

%----------------------------------------------------------------------------------------
%	SELECT OUTER THEME
%----------------------------------------------------------------------------------------
\useoutertheme{miniframes}

%----------------------------------------------------------------------------------------
%	PRESENTATION INFORMATION
%----------------------------------------------------------------------------------------
\title[Topic]{Subject}
\author[author]{author's name}
\institute[Org]{Org Name}
\date[September 30, 2024]{September 30, 2024}

%----------------------------------------------------------------------------------------
%	DOCUMENT
%----------------------------------------------------------------------------------------
\begin{document}

%-----------------------------------------------

\begin{frame} %{Vertical alignment (center)}
    \frametitle{Slide Title}
    % create a center environment, so that the contents appear at the center of the frame
    \begin{center}
        \begin{tikzpicture}
            {\node (img1) {\includegraphics[height=4cm]{img/imgA.jpg}};}
            
            \pause
            
            {\node (img2) at (img1.south east)
            {\includegraphics[height=4.5cm]{img/imgB.JPG}};}
            
        \end{tikzpicture}
    \end{center}
\end{frame}

%-----------------------------------------------

\begin{frame}
    \frametitle{Slide Title}
    \begin{tikzpicture}[remember picture,overlay]
        \only<1->{\node[anchor=north west] (img1) at ([xshift=0.4cm,yshift=-2.5cm]current page.north west) 
            {\includegraphics[height=4cm]{img/imgA.jpg}};}
        
        \only<2>{\node (img2) at (img1.south east)
            {\includegraphics[height=4.5cm]{img/imgB.JPG}};}
    \end{tikzpicture}
\end{frame}

%-----------------------------------------------

\end{document} 
[TikZ_Troubleshooting.pdf](https://github.com/user-attachments/files/17497024/TikZ_Troubleshooting.pdf)

**Comment by hmenke** [comment]
This is not a MWE.

**Comment by christopherbabcock** [comment]
Can you tell me what is incorrect about my post?

**Comment by christopherbabcock** [comment]
> This is not a MWE.

@hmenke Can you tell me what is incorrect about my post?

**Comment by hmenke** [comment]
You considering this a "post" would be top of the list, I guess. Please use the community forums for these kinds of discussions, such as https://tex.stackexchange.com/

**Comment by hmenke** [comment]
Apologies for my rather discouraging tone yesterday.

Here is what your example would look like as a minimal working example (MWE). The TeX Live distribution includes a couple of example images that can be used with `\includegraphics` directly without further ado.

```latex
\documentclass{beamer}
\usetheme{Boadilla} % some theme with footer

\usepackage{graphicx}
\usepackage{tikz}

\begin{document}

\begin{frame}
  \begin{tikzpicture}
    \node (img1) {\includegraphics[height=4cm]{example-image-a}};
    \pause
    \node (img2) at (img1.south east) {\includegraphics[height=4cm]{example-image-b}};
  \end{tikzpicture}
\end{frame}

\end{document} 
```

| Frame 1 | Frame 2 |
| --- | --- |
| ![test-1](https://github.com/user-attachments/assets/48dca617-055e-4ea2-9c13-e0aca7f104b1) | ![test-2](https://github.com/user-attachments/assets/f479dbed-bc9c-4438-b372-ede194cff942) |

The problem is that `\pause` is not smart enough, i.e. there is no special handling of `\pause` inside a `tikzpicture` implemented in beamer. If at all, this is a bug in beamer. Here are some relevant discussions from the community forums:

- [\pause in tikzpicture breaks footline](https://tex.stackexchange.com/questions/21512/pause-in-tikzpicture-breaks-footline)
- [Missing footer on first Beamer slide of TikZ example [duplicate]](https://tex.stackexchange.com/questions/10871/missing-footer-on-first-beamer-slide-of-tikz-example)
- [Beamer vs. TikZ: uncover nodes step-by-step](https://tex.stackexchange.com/questions/9094/beamer-vs-tikz-uncover-nodes-step-by-step)
- [Beamer \pause with TikZ](https://tex.stackexchange.com/questions/13960/beamer-pause-with-tikz)
- [Using \pause inside a tikzpicture environment in a beamer presentation](https://tex.stackexchange.com/questions/319400/using-pause-inside-a-tikzpicture-environment-in-a-beamer-presentation)

The easiest workaround for this problem is to explicitly tell beamer what to show on what slide with the `\onslide` command and using overlays:

```latex
\documentclass{beamer}
\usetheme{Boadilla} % some theme with footer

\usepackage{graphicx}
\usepackage{tikz}

\begin{document}

\begin{frame}
  \begin{tikzpicture}
    \onslide<+->{\node (img1) {\includegraphics[height=4cm]{example-image-a}};}
    \onslide<+->{\node (img2) at (img1.south east) {\includegraphics[height=4cm]{example-image-b}};}
  \end{tikzpicture}
\end{frame}

\end{document} 
```

| Frame 1 | Frame 2 |
| --- | --- |
| ![test-1](https://github.com/user-attachments/assets/d0f53524-9950-4d4f-9efe-9c2a0e6387b6) | ![test-2](https://github.com/user-attachments/assets/7d8726e0-561e-4204-bac2-185b1de0e6f2) |

**Comment by christopherbabcock** [comment]
I appreciate your very thorough response @hmenke. After looking at some forums, I thought it was a bug, which is why I didn't post to a forum. Again, thanks for providing a detailed response and guidance for what I should post in the future should I have an issue. Much appreciated!
