### ISSUE TITLE
adding `hatch pattern` to `pattern` library?

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#602]
*Migrated from SourceForge*
Author: mo-gul
Timestamp: 2013-11-09 12:16:36.907000

Hello developers,

it would be nice if you could add the `hatch pattern` presented at http://tex.stackexchange.com/questions/29359/pgfplots-how-to-fill-the-area-under-a-curve-with-oblique-lines-hatching-as-a
to the `pattern` library.

Many thanks in advance and best regards,
Stefan

**Comment by hmenke** [comment]
@Mo-Gul I was thinking about this today and came to the conclusion that this completely defeats the currently present optimization for patterns.  Right now, a pattern is only copied to the PDF once and when it is reused, the existing pattern is referenced which helps keeping the PDF file size in a reasonable limit.  When you have “mutable” patterns, which can change on each invocation, you completely lose the benefit of this optimization.  Instead of varying stroke thickness and line distance to suggest different patterns to the reader, the author should just use actually different patterns.

Using different patterns is also nicer for the visually impaired.

**Comment by ilayn** [comment]
This doesn't hurt the optimization. Jake's parametrization puts the atom tile of invocation to PDF still once. Hence the benefit is still there per invocation. You don't need to keep track of that optimization for the different calls with different parameters since it's strictly a user problem.

**Comment by hmenke** [comment]
@Mo-Gul Is this okay for you?
```latex
\documentclass[tikz]{standalone}
\usetikzlibrary{patterns.meta}

\tikzdeclarepattern{
  name=hatch,
  parameters={\hatchsize,\hatchangle,\hatchlinewidth},
  bounding box={(-.1pt,-.1pt) and (\hatchsize+.1pt,\hatchsize+.1pt)},
  tile size={(\hatchsize,\hatchsize)},
  tile transformation={rotate=\hatchangle},
  defaults={
    hatch size/.store in=\hatchsize,hatch size=5pt,
    hatch angle/.store in=\hatchangle,hatch angle=0,
    hatch linewidth/.store in=\hatchlinewidth,hatch linewidth=.4pt,
  },
  code={
      \draw[line width=\hatchlinewidth] (0,0) -- (\hatchsize,\hatchsize);
  }
}

\begin{document}
\begin{tikzpicture}
    \draw [pattern={hatch[hatch size=10pt, hatch linewidth=.8pt, hatch angle=10]}, pattern color=red]    (0,0) rectangle ++(2,2);
    \draw [pattern={hatch[hatch size= 5pt, hatch linewidth=.8pt, hatch angle=40]}, pattern color=blue]   (2,0) rectangle ++(2,2);
    \draw [pattern={hatch[hatch size=10pt, hatch linewidth=.4pt, hatch angle=90]}, pattern color=green]  (0,2) rectangle ++(2,2);
    \draw [pattern={hatch[hatch size= 2pt, hatch linewidth= 1pt, hatch angle=70]}, pattern color=orange] (2,2) rectangle ++(2,2);
\end{tikzpicture}
\end{document}
```
Most viewers have problems with anti-aliasing.
![test](https://user-images.githubusercontent.com/1903556/60570049-3b5eca80-9d60-11e9-8aac-8a52e6a39386.png)

**Comment by Mo-Gul** [comment]
As I already stated elsewhere (hopefully) you did an awesome work.

Doing some tests I could raise two errors; I added some comments in the following code. I think you will be able to modify the implementation code so that the usage will be possible (like with all other code).

Also I improved the definition of the `lines` pattern.

1. The biggest shortcoming/deficiency is the too small bounding box (`old lines`). This is because you didn't account for the line width. Correcting this gives the `improved lines`.
2. I (personally) think that it is counterintuitive that providing `angle=0` gives lines that actually have an angle of 45°.
3. I  (personally) think that `size` should give the *perpendicular* distance between the lines which is not the case (see the additionally drawn lines in the `improved lines` example.

To overcome all three shortcomings I adjusted your code to `new lines`. What do you think of that version compared to yours?

4. And I would wish another feature for the `lines`. That would be to `shift` the lines so that I could e.g. draw another line pattern *between* the "green" ones in another color using another `\path` command. But currently I don't have an idea for the implementation of that feature. Do you have one?

```latex
\documentclass[border=5pt]{standalone}
\usepackage{pgfplots}
    \usetikzlibrary{patterns.meta}
    % copied from `pgfmanual-en-library-patterns.tex` and changed the `name`
    \tikzdeclarepattern{
        name=old lines,
        parameters={
            \pgfkeysvalueof{/pgf/pattern keys/size},
            \pgfkeysvalueof{/pgf/pattern keys/angle},
            \pgfkeysvalueof{/pgf/pattern keys/line width},
        },
        bounding box={
            (-.1pt,-.1pt) and
            (\pgfkeysvalueof{/pgf/pattern keys/size}+.1pt,
             \pgfkeysvalueof{/pgf/pattern keys/size}+.1pt)
        },
        tile size={
            (\pgfkeysvalueof{/pgf/pattern keys/size},
             \pgfkeysvalueof{/pgf/pattern keys/size})
        },
        tile transformation={rotate=\pgfkeysvalueof{/pgf/pattern keys/angle}},
        defaults={
            size/.initial=5pt,
            angle/.initial=0,
            line width/.initial=.4pt,
        },
        code={
            \draw[line width=\pgfkeysvalueof{/pgf/pattern keys/line width}]
                (0,0) -- (\pgfkeysvalueof{/pgf/pattern keys/size},
                          \pgfkeysvalueof{/pgf/pattern keys/size});
        },
    }
    \tikzdeclarepattern{
        name=improved lines,
        parameters={
            \pgfkeysvalueof{/pgf/pattern keys/size},
            \pgfkeysvalueof{/pgf/pattern keys/angle},
            \pgfkeysvalueof{/pgf/pattern keys/line width},
        },
        bounding box={
            (
                -0.5*\pgfkeysvalueof{/pgf/pattern keys/line width},
                -0.5*\pgfkeysvalueof{/pgf/pattern keys/line width}
            ) and (
                \pgfkeysvalueof{/pgf/pattern keys/size}
                + 0.5*\pgfkeysvalueof{/pgf/pattern keys/line width},
                \pgfkeysvalueof{/pgf/pattern keys/size}
                + 0.5*\pgfkeysvalueof{/pgf/pattern keys/line width}
            )
        },
        tile size={
            (
                \pgfkeysvalueof{/pgf/pattern keys/size},
                \pgfkeysvalueof{/pgf/pattern keys/size}
            )
        },
        tile transformation={
            rotate=\pgfkeysvalueof{/pgf/pattern keys/angle},
        },
        defaults={
          size/.initial=4pt,
          angle/.initial=0,
          line width/.initial=0.5pt,
        },
        code={
            \draw [
                line width=\pgfkeysvalueof{/pgf/pattern keys/line width},
            ] (0,0) --
              (
                \pgfkeysvalueof{/pgf/pattern keys/size},
                \pgfkeysvalueof{/pgf/pattern keys/size}
              )
            ;
        },
    }
    % "new" definition
    \tikzdeclarepattern{
        name=new lines,
        parameters={
            \pgfkeysvalueof{/pgf/pattern keys/size},
            \pgfkeysvalueof{/pgf/pattern keys/angle},
            \pgfkeysvalueof{/pgf/pattern keys/line width},
        },
        bounding box={
            (
                0,
                -0.5*\pgfkeysvalueof{/pgf/pattern keys/line width}
            ) and (
                \pgfkeysvalueof{/pgf/pattern keys/size},
                0.5*\pgfkeysvalueof{/pgf/pattern keys/line width}
            )
        },
        tile size={
            (
                \pgfkeysvalueof{/pgf/pattern keys/size},
                \pgfkeysvalueof{/pgf/pattern keys/size}
            )
        },
        tile transformation={
            rotate=\pgfkeysvalueof{/pgf/pattern keys/angle}
        },
        defaults={
          size/.initial=4pt,
          angle/.initial=45,
          line width/.initial=0.5pt,
        },
        code={
            \draw [
                line width=\pgfkeysvalueof{/pgf/pattern keys/line width},
            ] (0,0) --
              (
                \pgfkeysvalueof{/pgf/pattern keys/size},
                0
              )
            ;
        },
    }
\begin{document}
\begin{tikzpicture}
    % old version
    \draw [
        pattern={
            % remove the comment sign in the next line to get an error
            % add a space before the `[` to get another error
            old lines[%
                size = 10pt,
                line width = 2pt,
                angle = 0,
            ]
        },
        pattern color = red,
    ] (0,0) rectangle ++(2,2);

    % improved version
    \draw [
        pattern={improved lines[size=10pt,line width=2pt,angle=0]},
        pattern color=blue,
    ] (2,0) rectangle ++(2,2);
    \draw [blue!50]         (2.96,0.2) -- ++(135:10pt);
    \draw [blue!35]         (2.96,0.2) -- ++( 90:10pt);

    % new version
    \draw [
        pattern={new lines[size=10pt,line width=2pt,angle=45]},
        pattern color=green,
    ] (4,0) rectangle ++(2,2);
    \draw [green!50!black]  (5.12,0.2) -- ++(135:10pt);
\end{tikzpicture}
\end{document}
```
![image showing the result of above code](https://user-images.githubusercontent.com/17992976/64193657-7aeb8500-ce7d-11e9-8a5f-57c3a34439fb.png)

**Comment by Mo-Gul** [comment]
What do you think about providing either an additional sub-libraries with some general implementation of the "most used patterns" or providing them directly with `patterns.meta`. I think that the "most used patterns" will be the ones that are already given in the `pattern` library. So that would be something like

- `horizontal lines`, `vertical lines`, `north east lines`, `north west lines` --> `Lines`
- `grid`, `crosshatch` --> `Hachures`
- `dots`, `crosshatch dots` --> `Dots`
- `fivepointed stars`, `sixpointed stars` --> `Stars`
- `bricks` --> `Bricks`
- `checkerboard` --> `Checkerboard`

I suggest to use capital names, because this would be consistent to the `arrows.meta` library. What do you think?

**Comment by hmenke** [comment]
Thanks for testing.  Your suggestions make perfect sense to me.  Let's see when I have time to implement this.

**Comment by Mo-Gul** [comment]
As I have seen you have a roadmap for the next release.

Maybe it is worth it to replace the current "*old lines*" definition in the manual with the "*new lines*" (see [this comment](https://github.com/pgf-tikz/pgf/issues/602#issuecomment-527564693)) until you have found the time to implement the "most used patterns" directly in the `patterns.meta` library as suggested in [another comment](https://github.com/pgf-tikz/pgf/issues/602#issuecomment-527573213)?

**Comment by Mo-Gul** [comment]
Since you closed this issue I opened two others which are mentioned above and that you agreed are useful ...
- issue https://github.com/pgf-tikz/pgf/issues/775
- issue https://github.com/pgf-tikz/pgf/issues/776
