### ISSUE TITLE
/.code keys don't respect /.initial

### ISSUE THREAD

**Issue by hmenke** [pgf-tikz/pgf#654]
If a keys has been defined with `/.code`, the initial value can't be set with `/.initial`.  The following MWE shoud throw an undefined control sequence error when trying to set `/.initial` but that does not happen.
```latex
\input pgfkeys.tex
\pgfkeys{foo/.code=\ERROR}
\pgfkeys{foo/.initial=bar}
%\pgfkeys{foo=bar} % BOOM
\bye
```
This behaviour should either be fixed or documented.

**Comment by ilayn** [comment]
I vaguely remember fixing this somewhere maybe on TeX.SX or somewhere else. Here `/.initial` is trying to pass the value to the `/.style` handler since it can coexist with `/.code` with the same key name. If not set already, defining a dummy `/.style` fixes this.

**Comment by muzimuzhi** [comment]
- `.code` defines `\pgfk@<current path>/.@cmd` and `\pgfk@<current path>/.@body`, and `.initial` defines `\pgfk@<current path>`.
 - In execution, full key `\pgfkeyscurrentkey/.@cmd` has higher precedence than `\pgfkeyscurrentkey`. This logic hasn't changed for more than 10 years. See [related source lines](https://github.com/pgf-tikz/pgf/blob/54af91f0b247a2d147db67ef58e2271814a68d29/tex/generic/pgf/utilities/pgfkeys.code.tex#L350-L361).
 - Since `\pgfkeysifassignable` uses `\pgfkeysifdefined{#1/.@cmd}` to check the existence of command keys, it might be enough to always un-define `\pgfk@<current path>/.@cmd` in definition of `.initial`.

Hence here is a proposed change:
```diff
diff --git a/tex/generic/pgf/utilities/pgfkeys.code.tex b/tex/generic/pgf/utilities/pgfk
eys.code.tex
index f2288175..dd39d381 100644
--- a/tex/generic/pgf/utilities/pgfkeys.code.tex
+++ b/tex/generic/pgf/utilities/pgfkeys.code.tex
@@ -793,7 +797,10 @@

 % Defining a value

-\pgfkeys{/handlers/.initial/.code=\pgfkeyssetvalue{\pgfkeyscurrentpath}{#1}}
+\pgfkeys{/handlers/.initial/.code=%
+  \pgfkeyslet{\pgfkeyscurrentpath/.@cmd}\undefined
+  \pgfkeyssetvalue{\pgfkeyscurrentpath}{#1}%
+}
 \pgfkeys{/handlers/.add/.code 2 args=\pgfkeysaddvalue{\pgfkeyscurrentpath}{#1}{#2}}
 \pgfkeys{/handlers/.prefix/.code=\pgfkeysaddvalue{\pgfkeyscurrentpath}{#1}{}}
 \pgfkeys{/handlers/.append/.code=\pgfkeysaddvalue{\pgfkeyscurrentpath}{}{#1}}
```

**Comment by muzimuzhi** [comment]
PS: Currently, `.initial` is classified as handlers that define value-keys, which are different from handlers like `.code` that define command-keys. These two kinds of handlers represent different usages of `pgfkeys`, hence the above code made `.initial` and `.code` mutually exclusive, rather than compatible. 

This is different from `.default`, which uses `\pgfk@<current path>/.@def` to store the default value, and different from utilities of corresponding handlers in latex3 package `l3keys`.

Does it worth to make `.initial`, like `.default`, compatible with `.code`?

**Comment by hmenke** [comment]
Does the manual still compile with that?  If yes, please open a PR, then I'll ship it in the next release and we see what happens.

**Comment by muzimuzhi** [comment]
Manual compiles locally with luatex, but by reading implementation of handler `.add code`, I find `/.@args` need to be un-defined as well. I will prepare a PR containing this update.

(A less intelligent but always working approach is to un-define each of `/.@cmd, /.@body, /.@args, /.@@body`.)

**Comment by muzimuzhi** [comment]
> Does it worth to make `.initial`, like `.default`, compatible with `.code`?

This does the work:
```tex
\pgfkeys{/handlers/.initial/.code={%
  \pgfkeysifdefined{\pgfkeyscurrentpath/.@cmd}{%
    % similar to that used in \pgfkeys@case@one
    \pgfkeysgetvalue{\pgfkeyscurrentpath/.@cmd}{\pgfkeys@code}%
    \pgfkeys@code#1\pgfeov
  }{%
    \pgfkeyssetvalue{\pgfkeyscurrentpath}{#1}%
  }%
}}
```
With the above definition, after `\pgfkeys{foo/.code={...}}`,
```tex
\pgfkeys{foo/.initial=value}  % clearer semantic meaning
```
and
```tex
\pgfkeys{foo=value}           % already commonly seen in package codes using pgfkeys
```
are equivalent.

**Comment by marmotghost** [comment]
Seems like the update breaks previously working codes.
```latex
\documentclass{article}
\usepackage{pgf}
\begin{document}
\pgfkeys{/text/.store in=\mytext,
/text/.initial=pft
} 
\pgfkeys{/text=Hello} 
\mytext
\end{document}
```
This code is a bit nonsensical because `/.initial` should not be used like this but it did not lead to errors previously. This is just to say that this behavior is new and may lead to issue reports.

**Comment by muzimuzhi** [comment]
@marmotghost With https://github.com/pgf-tikz/pgf/commit/0f52b63caa8b69ea10f1c5e1dc052244fb85a8e5, yes in your example `\mytext` _is_ expected to be undefined.

There are currently two different ways to use `pgfkeys`, or at least two.
 - first kind is to store value in and retrieve value from keys, and
 - second is to assign codes to keys and execute codes by using keys.

Most handlers which defining keys, including `.code`, `.style`, and `.store in`, belong to the second kind, but as previously implemented and documented, `.initial` belongs to the first kind. Unfortunately, the name "initial" is so general that users may think that `.initial` will work for both kinds. Hence there are two usages that their behavior were not clearly specified before:
 - <strike>A key firstly defined as first kind, then second kind, at last used.</strike> This is the example in https://github.com/pgf-tikz/pgf/issues/654#issuecomment-703204508. (_Edit:_ It belongs to the following case too.)
 - A key firstly defined as second kind, then first kind, at last used. This is the initial example, given in https://github.com/pgf-tikz/pgf/issues/654#issue-432779361.

From 3.1.6, every time `.initial` is used, the key is ensured to (re)set to the first kind. This way, `.initial` works for and only for first kind keys. Another solution is to make `.initial` work for both kinds, as suggested in https://github.com/pgf-tikz/pgf/issues/654#issuecomment-683332110. Different users might prefer different solutions/improvments.

Considering how long and widely `pgfkeys` has been existed and used, there is not much room for improvement. Nearly every change will cause some new problems, either now-broken un-documented (tricky) usage or truly regression. If there is a chance to implement a new `pgfkeys`-like key management utility from scratch, I vote for some bit of pseudo type-system and more general handlers.

**Comment by marmotghost** [comment]
@muzimuzhi I know this, and I agree. But as you say the name can lead to misinterpretations, and correspondingly you find examples on Q & A sites which used it in a nonsensical way. Now the same codes will lead to errors. My remark was just to give a heads up. 
And yes, I'd also love to see a more general version. But these days pgf seems to be under siege because of the way expl3 deals with spaces. So I guess the most urgent task is to keep things alive. And it is probably fair to say that generally the keys have not been fully exploited, handlers like `/.search also` and `/.try` are very powerful but do not really seem to show up in too many examples.

**Comment by hmenke** [comment]
I've reverted the fix and reopened the issue.  No new errors should be introduced for previously accepted behaviour.

**Comment by muzimuzhi** [comment]
In very rare but still possible cases, after `\pgfkeys{/text/.store in=\mytext, /text/.initial=pft}`, user might expect neither of 
 - definitions of macros `\pgfk@/text/.@cmd`,  `\pgfk@/text/.@body`, and `\pgfk@/text`, and
 - behavior of following `\pgfkeys{/text=Hello}`, which should execute `\def\mytext{Hello}`

would change. Therefore nothing can be done here, but documenting the behavior: when both handlers `.code` (including all others derived from it) and `.initial` are used to the same `<key>`, `<key>=<value>` always uses `.code` but `\pgfkeysgetvalue`/`\pgfkeysvalueof` and `<key>/.initial` still work.

```tex
\documentclass{article}
\usepackage{pgf}
\begin{document}
\pgfkeys{
  /text/.store in=\mytext,
  /text/.initial=pft
}
\pgfkeys{/text=Hello}
\mytext, \pgfkeysvalueof{/text} % print "Hello, pft"

\pgfkeys{/text/.initial=tfp}
\pgfkeys{/text=World}
\mytext, \pgfkeysvalueof{/text} % print "World, tfp"
\end{document}
```

**Comment by ilayn** [comment]
This is a rare occasion that Till, in my opinion, made a mistake naming this key. Because it should have been `.initialize` and not `.initial`. That's why most people, myself for a long time, confused this with `.default` to make sure that the underlying macro is set something and not left undefined. 

So in that sense `\mytext` in @marmotghost 's example is not expected to be undefined if you are just a LaTeX user and not a tinkerer and it is very much sensical. I only found this out after reading the second paragraph of `.initial` in the manual a bit more than a hundred times in the past. The underlying machinery is maybe not optimal but the way it is presented to users is what matters.

If you want the default argument to be passed when omitted at the runtime you use `.default`, if you want to `get` the value from a key or use `valueof` you need `.initial` to make your code cold-start.

**Comment by hmenke** [comment]
Not only is it semantically confusing, it also seems to be unnecessary.  For those keys where it works `key/.initial=value` seems to be indistinguishable from `key=value`.

**Comment by ilayn** [comment]
That's also explained in the first paragraph. 

> No subkeys are involved 

With `key=value` that's not the case. Manual needs some polishing around these.

**Comment by muzimuzhi** [comment]
1. After being defined, a key can always be initialized by `key=value`. Hence initialization handler is always sth like syntactic sugar.
1. But if the macros creating and setting keys are split, then an initialization handler allowed in key creation will make codes more compact/clear. For example, in `l3keys`, keys are created by `\keys_define:nn{<module>}{<kv list>}` and set by `\keys_set:nn{<module>}{<kv list>}`. Hence
    ```tex
    \keys_define:nn {mymodule}
      {
        keyname .code:n    = Some~ code,
        keyname .initial:n = some~ value
      }
    ```
    is a bit better than
    ```tex
    \keys_define:nn {mymodule} { keyname .code:n    = Some~ code }
    \keys_set:nn    {mymodule} { keyname .initial:n = Some~ value }
    ```
1. Since `\pgfkeys` plays both the roles for key creation and setting, the necessity for having an init handler is little.

Finally, considering `pgfkeys` already has `\pgfkeys(set|get)value` and `/.get`, how about having a new handler `/.set` which plays the role of `/.initial` in https://github.com/pgf-tikz/pgf/commit/0f52b63caa8b69ea10f1c5e1dc052244fb85a8e5 (sets value to key without subkeys involved, and clears subkeys defined by `/.code` variants)?

**Comment by dbitouze** [comment]
I didn't read carefully the comments of this issue but I would like to point out in passing that a class of mine which makes use of `pgfkeys` and `.initial`:

- was broken since 3.16,
- works again with the @hmenke's commit bf46600.

I hope this fix will soon find its way to CTAN.

**Comment by dbitouze** [comment]
> I hope this fix will soon find its way to CTAN.

Unless you recommend me a better approach than `.initial` that would:
- bypass the current issue,
- be robust against the upcoming fixes regarding the current issue,
- let me make my class work again ASAP (before the upcoming fixes regarding the current issue).

**Comment by muzimuzhi** [comment]
@dbitouze That means in your class some keys are defined both by `/.initial` and by `/.code` variants, and personally I recommend to avoid doing that. The following small patch can be used to detect those keys:
```tex
\documentclass{article}
\usepackage{pgfkeys}
\usepackage{xpatch}

\makeatletter
\ifdefined\PackageWarning
  \def\pgfkeys@warning{\PackageWarning{pgfkeys}}%
\else
  \def\pgfkeys@warning#1{\immediate\write-1{%
    Package pgfkeys Warning: #1 on input line \the\inputlineno.}}%
\fi

\xpatchcmd\pgfkeys@case@one
  {\pgfkeysgetvalue}
  {\pgfkeysifdefined{\pgfkeyscurrentkey}
     {\pgfkeys@warning{Key `\pgfkeyscurrentkey' is defined both by `/.initial' and by `/.code' variants}}{}%
   \pgfkeysgetvalue}
  {}{\fail}
\makeatother

\begin{document}
\pgfkeys{my key/.initial=set val, my key/.code=run code}
\pgfkeys{my key=new val}
\end{document}
```
It will write warning message to log:
```
Package pgfkeys Warning: Key `/my key' is defined both by `/.initial' and by `/.code' variants on input line 22.
```
Ideally, those warning should be thrown when keys are defined, but that need to patch multiple places.

**Comment by hmenke** [comment]
@muzimuzhi That is a great idea!  Why didn't I think of that?  Could you please integrate that into `pgfkeys` proper and check whether the manual compiles without this particular warning?

**Comment by muzimuzhi** [comment]
@hmenke I've locally checked that the manual compiles without this particular warning. Note the warning only occurs when such keys are used, but not when defined (at the second time).

Steps:
 - apply https://github.com/muzimuzhi/pgf/commit/381138d68d23173818d89d1bfda253f83a3bf146
 - `texlua build.lua manual luatex`
- `grep -rni 'package pgfkeys warning' ./doc/generic/pgf/version-for-luatex/en/pgfmanual.log`

**Comment by muzimuzhi** [comment]
@hmenke In short, some utilities of `pgf` use/rely on keys defined both by `/.initial` and `/.code` variants. The manual compiles with a lot of that warning.

* In branch [`pgfkeys-warning-2`](https://github.com/muzimuzhi/pgf/commits/pgfkeys-warning-2), I first used a more radical method in https://github.com/muzimuzhi/pgf/commit/16081c4d580d4d42e4bbab529fc508cb9315b157, which patched places where keys are defined. For testing, `\pgfkeys@error`, instead of `\pgfkeys@warning` is deliberately used.
* This uncovered nine such keys, and I tried to resolve them kind by kind, and finally in https://github.com/muzimuzhi/pgf/commit/b2aa7ecce554957782a3dde1569816fed9092adc the manual compiles without errors. (Just a try, no warranty that the code behavior is unchanged.)
* In https://github.com/muzimuzhi/pgf/commit/0103e0c623f98ac669418b5eeab5cade36ed67b3, I applied the patch in https://github.com/pgf-tikz/pgf/issues/654#issuecomment-706527771, and that uncovered another five such keys defined by lua codes which I'm not familiar with.

It looks like currently `pgf` can neither change the behavior of `/.initial`, nor throw (warning) messages.

------
The first nine keys are
 * `/pgf/shape aspect`, in `pgflibraryshapes.geometric.code.tex` and `pgflibraryshapes.symbols.code.tex`, https://github.com/muzimuzhi/pgf/commit/7bbb0674378958c8549aff866d24e37d0a59861d
 * `/pgf/star point height` and `/pgf/star point ratio`, in `pgflibraryshapes.geometric.code.tex`, https://github.com/muzimuzhi/pgf/commit/a4a4e9a22e12917d23793a1aff4eada65dcb6ca1
 * `/tikz/data visualization/` keys `common`, `major`, `minor`, `subminor`, in `tikzlibrarydatavisualization.code.tex`, https://github.com/muzimuzhi/pgf/commit/9491821b0cb8ee31274a333ce889cfa0ec7a4428 and https://github.com/muzimuzhi/pgf/commit/96d7c1254290ac1c9b3def0416ef3df5d8475645 (rather uncertain whether the patch works)
 * `/tikz/graphs/radius`, in `tikzlibrarygraphs.code.tex`, https://github.com/muzimuzhi/pgf/commit/b2aa7ecce554957782a3dde1569816fed9092adc. This is actually caused by the `/.forward to` executed by `\pgfgdappendtoforwardinglist{/tikz/,/tikz/graphs/}` in `tikzlibrarygraphdrawing.code.tex`.

The next five keys are
```
/tikz/graphs/new edge to
/tikz/graphs/no span edge
/tikz/graphs/regardless at
/tikz/graphs/sibling distance
/tikz/graphs/simple necklace layout
```

**Comment by ilayn** [comment]
> After being defined, a key can always be initialized by `key=value`. Hence initialization handler is always sth like syntactic sugar.

Unfortunately no, as far as the API goes. As you discovered some of these keys, you have to `shape=star` then `key=this` or `key=that` to initialize everything which is not something you would like to do in a library file. Especially when there is `./code` associated with it which might require something that is not ready yet. "I don't want to use the key, I just want to initialize it".

Also you can modify the initialization by modifying the behavior of `./initial` from a central place. Using `key=value` to initialize their values is just bad API design which I would speculate the reason for the existence of `./initial(ize)` in the first place.

**Comment by dbitouze** [comment]
@muzimuzhi Thanks for your patch. I succeeded by removing all the `.initial` declarations in keys that were defined also with `.code`.

**Comment by muzimuzhi** [comment]
Let me add something as a short conclusion (compared to the long discussions) to save time for any future readers.

**Before 3.1.6**, after `key/.initial=val` and `key/.code=\cmd{#1}` (or any other handlers that define sub-key `.@cmd`), which one used first is irrelevant, 
 - using `\pgfkeys{key=<value>}` will execute `\cmd{<value>}` (the `<value>` might be empty),
 - using `\pgfkeys{key}` will execute `\cmd{<default value>}`, where `<default value>` is either `\pgfkeysnovalue` or any value set by `/.default`. 

In short, whenever sub-key `.@cmd` is used, using `key` will always execute commands, and the stored value has nothing to do with the passed value.

**In 3.1.6 and 3.1.6a**, the above behavior was changed such that `key/.initial` will eliminate effects caused by any previously used `key/.code`. This change didn't break `pgf-tikz` itself because it always uses `key/.initial` before `key/.code`, but will break user inputs.

**Since 3.1.7**, the change was restored. So the change influences only 3.1.6 and 3.1.6a.

**Since the next release**, users will see some clarification words in the doc of `/.initial` and the corresponding code behavior is guaranteed to not change in future releases.
