### ISSUE TITLE
Using @ in a nested .ecode does not work anymore (works in 3.0.1)

### ISSUE THREAD

**Issue by fshaked** [pgf-tikz/pgf#669]
The minimal example below, which works with pgf 3.0.1, now fails with this error:
```
./test.tex:13: Undefined control sequence.
<inserted text> \some
                      @val
l.13 \tikzset{a}
```

The example:
```
\documentclass{article}
\usepackage{tikz}

\makeatletter
\def\some@val{}
\tikzset{
  a/.style={
    b/.ecode={\some@val},
  }
}
\makeatother

\tikzset{a}

\begin{document}
empty
\end{document}
```

**Comment by hmenke** [comment]
Without having looked into this, it might be because of `\scantokens` in this bit
https://github.com/pgf-tikz/pgf/blob/8aa15cc936782f933db84543a92820c1ce485284/tex/generic/pgf/utilities/pgfkeys.code.tex#L76-L80
which is unfortunately needed if `/.code` takes arguments.  Otherwise you run into the hash doubling problem.

**Comment by hmenke** [comment]
Workaround:  Use `\csname...\endcsname`
```latex
\tikzset{
  a/.style={
    b/.ecode={\csname some@val\endcsname},
  }
}
```

**Comment by hmenke** [comment]
Related: https://github.com/pgf-tikz/pgf/issues/305

**Comment by hmenke** [comment]
@polgab You opened https://github.com/pgf-tikz/pgf/issues/305 long time ago and I merged your patch, but this led to the present issue.  I'm tempted to revert back to the old behaviour.
