### ISSUE TITLE
specifying node anchor in \draw produces orthogonal arrow tip at edge start

### ISSUE THREAD

**Issue by jkhsjdhjs** [pgf-tikz/pgf#688]
The following MWE
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
    \begin{tikzpicture}[nodes={draw}]
        \node (A) at (0, 0) {A};
        \node (B) at (2, 0) {B};
        \draw[->]
            (A.east) edge (B);
    \end{tikzpicture}
\end{document}
```
compiles to the following output:
![orthogonal arrow tip at edge start](https://screens.totally.rip/2019/06/5cf67aefb1aa0.png)

Removing `.east` from `(A.east)` generates the correct output I would also expect to see with `.east`:
![correct output](https://screens.totally.rip/2019/06/5cf69755b21c1.png)

I'm using TeXLive on Arch Linux, all packages are up to date:
``` 
>> ~ % sudo tlmgr update --all
tlmgr: package repository http://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet (verified)
tlmgr: saving backups to /usr/local/texlive/2019/tlpkg/backups
tlmgr: no updates available
```

**Comment by loopspace** [comment]
The issue here is that because the anchor is specified, TikZ knows that the path needs to start with a `moveto` to wherever `A.east` happens to be.  An `edge` command, however, creates an entirely new path.  So `\draw (A.east) edge B;` creates two paths: one which is just a move to `A.east` and one which draws a line from `A.east` to `B`.

The path `\draw (A) edge (B);` doesn't create the first path because TikZ doesn't know which anchor on `A` to use and goes into a "wait and see" state in that it waits to see where the other end of the path segment will be before it figures out what coordinate `A` should refer to.  The main path (ie not the `edge` path) never specifies another coordinate so TikZ never figures out what `A` refers to and therefore never resolves it to a specific coordinate.  Therefore `\draw (A) edge (B);` only creates the `edge` path.

Normally, the creation of this first path has no effect because it just consists of a single move.  What is happening here, though, is that you are decorating it with an arrow head.  Turns out that even paths that consist just of a move get an arrow head if you explicitly say that you want one.

To get the arrow head consistently on the `edge`, specify it as part of the `edge` path command, as in:

```
\draw (A.east) edge[->] (B);
```

This ensures that the options only apply to the edge path and not to the underlying path.

NB Using an edge by itself like this is not strictly necessary as an edge path is separate to the main path but if there isn't a main path you may as well construct the desired path as the main path.  So in this specific case, I would use a `to` instead of the `edge` which would avoid this issue.

**Comment by jkhsjdhjs** [comment]
Thanks for the detailed explaination, it was easy to follow!
Also thanks for the hint with `to`, it works perfectly!
Since this is rather an issue with my expectations I'm closing this.
