### ISSUE TITLE
Make the latest PDF manual available

### ISSUE THREAD

**Issue by johannesborgstrom** [pgf-tikz/pgf#704]
The README files state "See the file doc/generic/pgf/pgfmanual.pdf for a manual. This documentation also explains the installation."

There is no such file in the repo. 

Either change the README to point to a PDF version of the manual, or check one in.

**Comment by joulev** [comment]
https://pgf-tikz.github.io/. I think it is in the repo description itself.

**Comment by hmenke** [comment]
The file `doc/generic/pgf/pgfmanual.pdf` is generated from the sources in `doc/generic/pgf/text-en/`.  In principle I could add this file to the repo but it could easily get out-of-sync with the sources because I might forget to update the manual when updating the sources.  However, the manual is distributed with the release version of PGF and should be located in that exact location.  If you prefer to read the manual online, you can find the PDF version for the latest release on https://ctan.org/pkg/pgf or the SVG version for the latest `master` on https://pgf-tikz.github.io/ (as joulev already mentioned).

Nevertheless, I think it is a good idea to make the PDF available as well, probably through the tlcontrib repo.  I'm therefore marking this as a feature request.

**Comment by hmenke** [comment]
Fixed in https://github.com/pgf-tikz/pgf/commit/743b26a126bda0b55f280512ff3d7c64e8e7b7b4.
The latest PDF manual can be obtained from here: http://pgf-tikz.github.io/pgf/pgfmanual.pdf
