### ISSUE TITLE
\rawx,\rawy,\rawz do not seem to work 

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#731]
First of all, thanks a lot for adding `\coord` to the `calc` library. This works just great! However, what does not seem to work in general at this point are `\rawx`, `\rawy` and `\rawz`. To see this consider
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{calc}
\begin{document}
\begin{tikzpicture}
\path  let \p1=(1,2,3) in (0,0)  node{works: \rawx1,\rawy1,\rawz1};
\path (1,2,3) coordinate (a) (5,6,7) coordinate (b);
\path  let \p1=(b),\p2=(a) in (0,-2)  node{doesn't work: \rawx1,\rawy1,\rawz1};
\end{tikzpicture}
\end{document}
```
The coordinates seem to have forgotten that they were set with `\pgfpointxyz`. That is, the coordinates seem to be only available if one sets the coordinates explicitly in `let ... in` but not for symbolic coordinates. (If this does not get fixed, this is not a big deal because all relevant data is contained in `\coord`, it may just be more convenient to work with `\rawx`. BTW, if one could store in addition to `\coord` (and perhaps `\rawx`, `\rawy` and `\rawz`) also a 3x3 matrix or 3 rotation angles, it would be possible (and not even difficult) to store the coordinates in a frame-independent way.)

**Comment by hmenke** [comment]
This would require major restructuring of the core positioning code, because PGF would have to keep track of the active coordinate system for each point and perform the conversion to 2D canvas coordinates lazily at the end of the picture.  That is to say, once you assign
```latex
\coordinate (a) at (1,2,3);
```
the coordinate `a` is converted to `\pgfpoint` and all information about the coordinate system is lost.  The coordinate system is only accessible at the time of scanning the point `(1,2,3)` (see `\tikz@scan@one@point`).  I don't think this can be fixed within a reasonable amount of work and is very prone to introduce a lot of regressions.

**Comment by ghost** [comment]
I do not understand this. One would only have to store in addition to `\coord`, which, if I understand things correctly, get stored via

> \expandafter\xdef\csname tikz@dcl@coord@\tikz@fig@name\endcsname{%
> \csname tikz@scan@point@coordinate\endcsname}%

in tikz.code.tex, three more parameters, whose default values are 0. These are the rotation angles, which could/should be global. From these 6 values one could always compute the x, y and z coordinate in a reference coordinate system. And from those you could compute distances, angles between vectors and so on.

**Comment by hmenke** [comment]
That doesn't work in situations like
```latex
\coordinate (a) at (1,2,3);
\coordinate (b) at (a);
```
because the declared coordinate of `b` is `a` which has already been converted to `\pgfpoint`.  As I already said, if you wanted to do this properly you'd have to revise the whole core positioning code to make sure that things are properly kept track of.

Also your suggestion of storing rotation angle is very specific to the 3D coordinate system.  There are a lot of other coordinate systems available and also user-defined ones are possible.

**Comment by ghost** [comment]
What I do not understand is that `\coord` does work. All one would need in order to make 3d tracking feasible is to add a twin of `\coord`. This twin does not contain the raw input coordinates but the view angles at the time when the point was defined.

**Comment by hmenke** [comment]
Here is how `\coord` works:  When you define a coordinate like this
```latex
\coordinate (a) at (1,2,3);
```
a new global macro is defined which holds the “declared coordinate” of `a`, which in this case is the literal string `(1,2,3)`.  If you used, say polar coordinates like `(60:1cm)` than the macro would contain exactly that string.  That is to say, storage of the declared coordinate takes place *before* parsing it.  When you use `\coord` you query that global macro and if it is not empty, the declared coordinate is returned.  This obviously fails for declarations like
```latex
\coordinate (a) at (1,2,3);
\coordinate (b) at (a);
```
because now `b` does not actually have a “declared coordinate”.  At a low level, simply a different branch is taken in `\tikz@scan@one@point`, which does not include the global definition.

**Comment by hmenke** [comment]
BTW, what you observe is the expected behaviour of `\rawx`, etc. as documented in the commit message of https://github.com/pgf-tikz/pgf/commit/9467c171fe27adb468829f1b196b2b7b5b3a12ba:

> There is an issue with 3D coordinates being projected onto the 2D canvas.
> There is not way to reverse the projection because a system of two equations
> (the project 2D coordinates) with three unknowns (the original 3D coordiantes)
> is underdetermined and unsolvable.  Hence I introduce these new little helpers
> which can be used to access the parsed original coordinates.  This works only
> if you use literal coordinates in the let operation, i.e.
> 
>     \path let \p1=(1,2,3) in ...
> 
> will work as expected, but
> 
>     \coordinate (A) at (1,2,3);
>     \path let \p1=(A) in ...
> 
> will not work, because the projection has already been performed when defining
> the \coordinate.

**Comment by ghost** [comment]
Yes, I understand that. And this is all what is needed to track 3d coordinates. I plan to post an example later, but here is the idea. In general, it is as you say: you store some string which may have whatever meaning because it is not clear which frame these coordinates refer to. However, imagine now that you work in 3d, and all allowed transformations are changes of the view, i.e. orthogonal transformations. Then the above-mentioned string plus the information about the three rotation angles uniquely specify the location of the point in a "universal" frame. This is all one needs to be able to compute coordinate-independent quantities like distances, angles between vectors (everything that transforms as a scalar). For most of the applications, at least those in the standard questions, this would be an extremely important addition. Without storing the angles one can do all these things in one frame, which is IMHO already quite something, see https://tex.stackexchange.com/a/504934/194703. Yet many additional applications would arise if one could switch to a frame in which, say, the z axis points in a desired direction.

**Comment by hmenke** [comment]
I see, so the issue is actually not that “\rawx,\rawy,\rawz do not seem to work” but that you want more features.  Please change the title accordingly and tag it as a feature request.

**Comment by ghost** [comment]
Would it be cleaner to close this one and to open another one? The thing which we were discussing here was just a BTW: "BTW, if one could store in addition to \coord (and perhaps \rawx, \rawy and \rawz) also a 3x3 matrix or 3 rotation angles, it would be possible (and not even difficult) to store the coordinates in a frame-independent way.)" The purpose of this issue was really to gauge whether the fact that \rawx etc. are empty for symbolic coordinates is a bug or intended. (Most likely one could add them to tikz.code.tex, but this just doubles the information, so is not important. But I do not understand what the purpose of \rawx etc is. Maybe one could drop them?)

**Comment by hmenke** [comment]
Right now the behaviour of `\rawx`, etc. and `\coord` is intended.  I have documented the shortcomings in the corresponding commit messages https://github.com/pgf-tikz/pgf/commit/9467c171fe27adb468829f1b196b2b7b5b3a12ba and https://github.com/pgf-tikz/pgf/commit/31165f2f43d419e1a921a1881bf25743592577a7.
This clearly needs a lot more thought, because what do you do about points like this?
```latex
\draw (20:1) -- coordinate (a) +(1,2,3);
```
The coordinate `a` is placed midway between two points from different coordinate systems, which makes perfect sense in 2D canvas coordinates, but is hard to describe retaining information about the coordinate system.
In a first approximation the whole information about a point, including the coordinate system it was specified in should be stored using PGF keys to avoid the proliferation of macros.

**Comment by ghost** [comment]
Yes, on the one hand, examples like 

> \draw (20:1) -- coordinate (a) +(1,2,3);

can lead to headache but on the other hand such constructions do not make too much sense IMHO. There is not much point in trying to add a 3-vector to a 2-vector, so users should not complain if in such a construction derived points behave unexpectedly. One way to deal with this is to promote all 2d points to 3d points, i.e. (20:1) will be associated with (cos(20),sin(20),0). That is, all 2d points get a z coordinate 0. 

The problem of attaching pgf keys everywhere is that this essentially doubles the effort. So this will never be as user friendly as your `\coord` already is. See https://tex.stackexchange.com/a/176241/194703 for an actual implementation and its downsides. (I am not saying the answer is bad, it is not at all bad, but you see that you cannot just define points in the usual nice Ti*k*Zy way.)

But in any case the current issue is IMHO closed since your links provide all information that I was looking for.

**Comment by hmenke** [comment]
I intend to close this be removing `\raw<x,y,z>` and `\coord` again.  They were never documented and the experiment has clearly failed.  I will however retain access to the “declared” coordinates of points (https://github.com/pgf-tikz/pgf/commit/dda04d3fc57378dcc178f74a8544480af5f2300a).  This might come in handy at some point.

**Comment by ghost** [comment]
I strongly object to this. You seem not have had a look at 3dTools at all,
you were only seeing `tikz-3dplot`. which is not at all needed. Well, if
you want to destroy the work of many hours, go ahead, but do not expect
anyone to ever try to do something that extends Ti*k*Z in any way. I will
make sure that they learn what happened here.

**Comment by hmenke** [comment]
There are some strong feeling involved here.  As far as I can see, this issue has nothing to do with 3dtools.  Your 3dtools library does not make use of either `\raw<x,y,z>` nor `\coord`, so I don't see how their removal destroys your works.  As mentioned in my earlier comment in this thread, access to the “declared” coordinates, which *is* used by 3dtools will stay.

**Comment by hmenke** [comment]
I removed `\raw<x,y,z>` and `\coord` now, but I repeat, `\tikz@dcl@coord@<name>` is still there!
