### ISSUE TITLE
[manual] Italics mistake in section 2.7

### ISSUE THREAD

**Issue by AlexDikelsky** [pgf-tikz/pgf#762]
![image](https://user-images.githubusercontent.com/52082790/67701487-036a3b80-f97e-11e9-961b-0c84b959a290.png)

The italics for the first 0 don't match the second. Also, maybe the 2 shouldn't be italicized for `step=2pt` 
This is in section 2.7 on page 34, using version:
```
The TikZ and PGF Packages 
Manual for version 3.1.4b
https://github.com/pgf-tikz/pgf
Till Tantau∗
Institut für Theoretische Informatik
Universität zu Lübeck
August 3, 2019
```

**Comment by hmenke** [comment]
The problem is in `\pgfmanual@pretty@pgfkeys@collectvalue`
https://github.com/pgf-tikz/pgf/blob/1302de8a99834bb0e30ffc214a7350952c446ab6/tex/latex/pgf/doc/pgfmanual.prettyprinter.code.tex#L1030-L1061
in particular this line:
https://github.com/pgf-tikz/pgf/blob/1302de8a99834bb0e30ffc214a7350952c446ab6/tex/latex/pgf/doc/pgfmanual.prettyprinter.code.tex#L1056
It just collects everything up to the next comma, which in this case, where there is only a single key, is inside the point `(0,0)`.
