### ISSUE TITLE
Anchor gets overwritten with "every label"

### ISSUE THREAD

**Issue by LarrySnyder** [pgf-tikz/pgf#773]
When using `anchor=base` for node labels so that the labels are aligned at their baselines, TikZ seems to respect the setting if I set the option in the label itself, but not if I set the option globally.

Please see my question at https://tex.stackexchange.com/q/515646/63847, as well as the answer at https://tex.stackexchange.com/a/515662/63847.

**Comment by hmenke** [comment]
Closing in favour of #774, because that is actually a proper bug report and not just a link to some external site.

**Comment by LarrySnyder** [comment]
OK. Sorry. This was my first time submitting a bug report on github so I didn’t know the protocol.

Larry

**Comment by hmenke** [comment]
I think it applies in general that developers are more interested in fixing the actual bugs rather than trying to make sense of the ticket by chasing links and piecing together information from third-party sites.

You can always *add* a link to your Stack Exchange post, but that does not replace a proper description of the bug and a minimal (non)working example.

**Comment by LarrySnyder** [comment]
OK, fair enough. To be honest I do not fully understand the bug or what causes it, so I figured it best to point to the MWE and discussion on Stack Exchange. In any case, I know for next time, and I appreciate your handling of the ticket—not to mention your work on TikZ, which I use extensively.

Larry
