### ISSUE TITLE
Missing entry to overlay-beamer-styles

### ISSUE THREAD

**Issue by Friedrich2** [pgf-tikz/pgf#828]
Version: 3.1.5b

In multiple tex.stackexchange.com questions like [this one](https://tex.stackexchange.com/questions/526581/how-to-stop-a-tikz-matrix-from-jumping-about-in-beamer), the library overlay-beamer-styles was an essential part of the problem solution, but this library is not documented in the manual.

Technical details may be found [here](https://tex.stackexchange.com/questions/174226/reference-on-tikz-and-beamer-overlay-specifications/175100#175100). I do not have any knowledge of TikZ or TeX, thus I am not able to resolve this issue.

PS: While creating a new issue, I found that the word "manual" in the first automatically-inserted comment falsely written. Perhaps this typing error is so simple to correct for a reader of this issue that a new Github issue is not needed.

**Comment by hmenke** [comment]
`overlay-beamer-styles` is not part of PGF/TikZ.

**Comment by Friedrich2** [comment]
I have to correct myself: The `beamer-overlay-styles` tikz library seems to be being provided by the package [`aobs-tikz`](https://www.ctan.org/pkg/aobs-tikz).
Neverthelesss, I was not able to find documentation for **simple overlay commands** like `\draw<2-> (A) to (B)` in the manual (by searching for `overlay` or `<2->` in the manual). Should it be documented in the PGF / TikZ manual? Should I open a new issue?

**Comment by hmenke** [comment]
TikZ is kind of overlay-aware, but not really.  Essentially it just stuffs commands into beamer's `\alt`, when the overlay specification is detected.
https://github.com/pgf-tikz/pgf/blob/0c14c1b0e19b704dc9f09027359fc6b7d1a64d95/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L2088-L2092
This is also the reason for all of the known problems that TikZ drawings move around on the slide because the bounding box changes with each overlay.

I'm not sure whether documenting this in the style of “sure you can do this, but it acutally does not work in this and this case” is any helpful.  Also people don't read the TikZ manual at all in the first place.
