### ISSUE TITLE
[rounded rectangle] causes random “divide by zero” PGF Math Error

### ISSUE THREAD

**Issue by rnollet** [pgf-tikz/pgf#908]
This originated as [a question on TeX-SX](https://tex.stackexchange.com/questions/557211/why-does-rounded-rectangle-cause-random-divide-by-zero-pgf-math-error), which @hmenke diagnosed as a pgf bug.

The following file `bug.tex`

```latex
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{shapes.misc}

\begin{document}

\tikz[remember picture]{\node (a) {a};}
\tikz[remember picture]{\node[rounded rectangle] (c) {c};}

\begin{tikzpicture}[remember picture, overlay]
  \draw (a) -- (c);
\end{tikzpicture}

\end{document}
```
when compiled with `rm -f bug.aux && pdflatex bug`, triggers the following error

```latex
! Package PGF Math Error: You asked me to calculate `1/0.0', but I cannot divid
e any number by zero.

See the PGF Math package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.14   \draw (a) -- (c)
                       ;
```

The weird thing being moreover that this error does not appear if you do any of these:

- remove `[rounded rectangle]`
- remove the `\draw` command
- `\draw (c) -- (a);` instead of `(a) -- (c)`
- change randomly the content of the nodes, for instance:
    * if you change the content of `(a)` to `{b}`, it works
    * if you change the content of `(c)` to `{b}`, it works
    * if you change the contents of both `(a)` *and* `(c)` to `{b}`, it does not work.

---

Two more remarks:

- The `[remember picture, overlay]` does not seem to be the source of the problem: the error still appears when I remove it. I keep it in the MWE because when this bug does not interrupt the compilation chain, removing it causes other problems later on.
- If you change one of the elements I mentioned above to make it compile, and then undo this change and recompile it without removing the `.aux` file, it may compile without a problem.
- If, during the compilation, you type `<return>` to proceed despite the error, you get
  ```latex
  ! Arithmetic overflow.
  <to be read again> 
                     \relax 
  l.14   \draw (a) -- (c)
                         ;
  ```
  if you proceed again with `<return>` and then recompile the document without removing the `.aux` file, this second compilation goes without error and outputs something that looks like what we expect.

**Comment by ilayn** [comment]
If I compile consecutively twice it works (error on first, success in second). It would have been better that it didn't work because this is a pathological example but it works.

**Comment by rnollet** [comment]
That’s right. I didn’t remark that because I always answer `X` to LaTeX errors. I’ve added this remark in the description.

**Comment by hmenke** [comment]
This always fails
```latex
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{shapes.misc}

\begin{document}

\begin{tikzpicture}
    \node[draw,rounded rectangle] (c) {x};
    \draw (0,0) -- (c);
\end{tikzpicture}

\end{document}
```
The problem comes from `\pgfpointintersectionoflines` which tries to invert the transformation matrix even when the start and end point of one of the lines coincide.  The code even documents that this fails but then that case has to be somehow avoided.

https://github.com/pgf-tikz/pgf/blob/0e9f8a60dac8199021670c9d248b47fba12fa95e/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex#L189-L191

**Comment by muzimuzhi** [comment]
> The problem comes from `\pgfpointintersectionoflines` which tries to invert the transformation matrix even when the start and end point of one of the lines coincide.

A more general question would be, how should `\pgfpointintersectionoflines` set `\pgf@x` and `\pgf@y` in degenerated cases, where the transformation matrix has zero determinant (hence cannot be inverted). There are at least three cases: (1) points `#1` and `#2` are identical, (2) points `#3` and `#4` are identical, and (3) lines `#1 -- #2` and `#3 -- #4` are parallel.

When `\pgfpointintersectionoflines`  is called by `tikz`, is it guaranteed that there must be an _unique_ intersection in those two possibly degenerated lines?

_Update:_ If the answer is yes, then cases (1) and (2) can be easily handled.

**Comment by hmenke** [comment]
I have thought about this some time ago and considered that `\pgfpointintersectionoflines` could just return `\pgfpointorigin` if there is no intersection.  However, that does not make any sense, because there just is no intersection, so it should not return a valid point.  Hence I think the current behaviour of `\pgfpointintersectionoflines` is fine (a better error message would maybe be nice) and it should just be avoided to call it with non-intersecting lines.

**Comment by muzimuzhi** [comment]
Another problem: in `\pgfpointshapeborder{<node>}{<point>}` ([current implementation](https://github.com/pgf-tikz/pgf/blob/6a28b6c2c154860c25f217616cee607a1a638f37/tex/generic/pgf/modules/pgfmoduleshapes.code.tex#L597-L633)), if `<point>` is identical to the center of `<node>`, the behavior is not specified.

Caused by tex's calculation errors, with some shapes, the line from `<node>` center to `<point>` does not degenerate to a single point, hence `pgfpointshapeborder` can still return a point on border. With shape `rounded rectangle`, the line degenerates hence an error is raised.

I think `\pgfpointshapeborder` should just return `<point>` if it is close enough (`< 0.0001pt`) to the `<node>` center (perhaps with a warning message saying "points XXX too close to the center of node XXX, result is not reliable"). I haven't understand the transformation macros used in `\pgfpointshapeborder` yet, hence cannot provide a proposal.

------

In the following example, 
 - black filled circles show the normal usages of `\pgfpointshapeborder`, and 
 - blue filled circles show the varied behavior when `<point>` is identical to the center of `<node>`.
```tex
\documentclass{article}
\usepackage{pgf, pgffor}
\usepgflibrary{shapes.misc}

\begin{document}
\foreach \i in {rectangle, circle, rounded rectangle} {
  \begin{pgfpicture}
    % helper grid
    \begin{pgfscope}
      \color{gray}
      \pgfpathgrid{\pgfpoint{-1cm}{-1cm}}{\pgfpoint{2cm}{1cm}}
      \pgfusepath{stroke}
    \end{pgfscope}
    
    \pgfnode{\i}{center}{Hello World!}{x}{\pgfusepath{stroke}}
    
    % <point> is different from center of <node>
    \pgfpathcircle{\pgfpointshapeborder{x}{\pgfpoint{2cm}{1cm}}}{2pt}
    \pgfpathcircle{\pgfpoint{2cm}{1cm}}{2pt}
    \pgfusepath{fill}
    
    % <point> is identical to center of <node>
    \color{blue}
    \pgfpathcircle{\pgfpointshapeborder{x}{\pgfpoint{0cm}{0cm}}}{2pt}
    \pgfpathcircle{\pgfpoint{0cm}{0cm}}{2pt}
    \pgfusepath{fill}
  \end{pgfpicture}
  \par
}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/92318383-3cfbe080-f03e-11ea-9506-86798bac5969.png)
