### ISSUE TITLE
\pgfpointanchor can insert spurious spaces if the anchor is an angle

### ISSUE THREAD

**Issue by marmotghost** [pgf-tikz/pgf#946]
**Brief outline of the bug**

`\pgfpointanchor` can insert spurious spaces if the anchor is an angle. This does not happen for "stringy" anchors like `west`.

**Minimal working example (MWE)**
```latex
\documentclass{article}
\usepackage{tikz}
\makeatletter
\pgfmathdeclarefunction*{x2d}{2}{%
\begingroup%
\pgf@process{\pgfpointanchor{#1}{#2}}%
\pgfmathparse{\pgf@x}%
\pgfmathsmuggle\pgfmathresult\endgroup%
}%
\pgfmathdeclarefunction*{test}{2}{%
\begingroup%
\pgfmathparse{0}%
\pgfmathsmuggle\pgfmathresult\endgroup%
}%
\makeatother
\begin{document}
\begin{tikzpicture} 
 \node[circle,draw,minimum size=2cm] (c) at (1,0) {};
 \draw (c.center)  -- ++ (0,2);
 \pgfmathparse{x2d("c","center")}
 \draw[blue,dashed] (c.center)  -- ++ (0,2);
 \pgfmathparse{x2d("c","20")}
 \draw[red,dashed] (c.center)  -- ++ (0,2);
\end{tikzpicture}
\begin{tikzpicture} 
 \node[circle,draw,minimum size=2cm] (c) at (1,0) {};
 \draw (c.center)  -- ++ (0,2);
 \pgfmathparse{test("c","center")}
 \draw[blue,dashed] (c.center)  -- ++ (0,2);
 \pgfmathparse{test("c","20")}
 \draw[red,dashed] (c.center)  -- ++ (0,2);
\end{tikzpicture}
\end{document}
```

<img width="366" alt="Screen Shot 2020-11-06 at 9 58 48 AM" src="https://user-images.githubusercontent.com/68924170/98398959-9bc9e000-2016-11eb-8ce4-e7e8ee3fa6be.png">

As you can see, the dashed red line gets shifted. This is not because the function uses strings (which is why there is a second picture with a function `test`). The problem is also absent if one uses nonnumerical anchors.

**Comment by hmenke** [comment]
This is not a MWE.

**Comment by marmotghost** [comment]
Your fix does not work.

**Comment by hmenke** [comment]
Works on my machine.

**Comment by Qrrbrbirlbel** [comment]
There are multiple spaces in the definitions of the anchors, the most common is the space after the opening `{`, e.g.
https://github.com/pgf-tikz/pgf/blob/584b5ffb88e577b567ad8653854965fe3a5be3bd/tex/generic/pgf/modules/pgfmoduleshapes.code.tex#L1015

Some libraries don't have those spaces at all, others have `%`ed some of those spaces but not all or also have them after `}` at the end of a line:

https://github.com/pgf-tikz/pgf/blob/584b5ffb88e577b567ad8653854965fe3a5be3bd/tex/generic/pgf/libraries/shapes/pgflibraryshapes.geometric.code.tex#L84-L92

---

Here's a simpler MWE.

Uncommenting any of the commented lines will place the circle at the correct point again.

In my own code, I've chosen to use `\nullfont` since removing the spaces in all anchors of all shapes isn't practable.

```latex
\documentclass[tikz]{standalone}
\pgfmathdeclarefunction{anglebetweencoordinates}{2}{%
  \begingroup
%    \nullfont
    \pgfmathanglebetweenpoints
      {\pgfpointanchor{#1}{center}}%
      {\pgfpointanchor{#2}{center}}%
    \pgfmathsmuggle\pgfmathresult
  \endgroup
}
\usepackage{etoolbox}
\makeatletter
%\patchcmd\pgf@anchor@rectangle@center{ \pgf@process}{\pgf@process}{}{\PatchFailed}
\makeatother
\begin{document}
\begin{tikzpicture}[nodes=draw]
\node (A) at (0,0)  {A}
 node (B) at (30:1) {B};
\draw (A.{180+anglebetweencoordinates("A","B")}) circle[radius=2pt];
\end{tikzpicture}
\end{document}
```
