### ISSUE TITLE
Using `positioning` on matrix node containing child node result in unexpected behavior. 

### ISSUE THREAD

**Issue by MathMapMat** [pgf-tikz/pgf#949]
When a matrix node is positioned `right = of` another node, the child node inside the matrix node will lean to the right.  
This phenomenon does not appear when using `below = of`. 

```latex
\documentclass[tikz]{standalone}
\usetikzlibrary{positioning}
\begin{document}
\begin{tikzpicture}
    [level distance = 10mm]

    \node [matrix, label=left:{$T_1$}] (T1)
    {
            \begin{scope}
                [every node/.style={draw, circle, inner sep=1pt, minimum size = 1mm}]
                \node {}
                child {node {} child {node {}}}
                child {node {} child {node {}}}
                child {node {} child {node {}}};
            \end{scope}\\
        };

    \node [matrix, right = of T1, label=left:{$T_2$}] (T2)
    {
            \begin{scope}
                [every node/.style={draw, circle, inner sep=1pt, minimum size = 1mm}]
                \node {}
                child {node {} child {node {}}}
                child {node {} child {node {}}}
                child {node {} child {node {}}};
            \end{scope}\\
        };

\end{tikzpicture}
\end{document}
```

**Comment by ilayn** [comment]
Since you are using the matrix as the placeholder, these matrices are single entry items. And hence the node options given to matrix applies also to the inner scope. So all nodes receive `anchor=west` implicitly in the second matrix. Add `anchor=center` to the second scope and it will be straight again. In the `below = of T1` case all are anchored `north` but visually you don't notice it since everything is straight.

You don't need the encapsulating matrices for this application or use `fit` library to draw thing around trees or explicitly place the second matrix via `at (<coordinate>)` syntax.

**Comment by MathMapMat** [comment]
> Since you are using the matrix as the placeholder, these matrices are single entry items. And hence the node options given to matrix applies also to the inner scope. So all nodes receive `anchor=west` implicitly in the second matrix. Add `anchor=center` to the second scope and it will be straight again. In the `below = of T1` case all are anchored `north` but visually you don't notice it since everything is straight.
> 
> You don't need the encapsulating matrices for this application or use `fit` library to draw thing around trees or explicitly place the second matrix via `at (<coordinate>)` syntax.

Thank you very much! This is a MWE. I was drawing a Hasse diagram where each element is a tree. And I want to make each tree of the same size and style. So I decided to use matrix node. I guessed that the problem comes from inheritance, but I thought they inherited the `right`, and couldn't find a way to reset it. Now it makes perfectly sense as they inherited anchor. 

Probably it would be nice to implent `matrix right = of` just as `matrix anchor`?

**Comment by ilayn** [comment]
I don't think matrices are good placeholders for your application. There are other ways to group partial drawings such as positioning scopes themselves, `pic`s or even just straight TeX `tabular`s. But in this case you can directly position the root nodes with much better control. The matrix won't give you any finer control benefits regarding positioning anyways.

```latex
\usetikzlibrary{positioning}
\begin{tikzpicture}[
  root/.style={draw, circle, inner sep=1pt, minimum size = 1mm},
  children/.style={draw, circle, inner sep=1pt, minimum size = 1mm}
]
\node[root] (root1) {} [every child node/.style=children]
child {node {} child {node {}}}
child {node {} child {node {}}}
child {node {} child {node {}}};
\node[root,right= 4cm of root1] (root2) {}
[every child node/.style=children]
child {node {} child {node {}}}
child {node {} child {node {}}}
child {node {} child {node {}}};
\node[root,below left= 3cm and 2cm of root1] (root3) {}
[every child node/.style=children]
child {node {} child {node {}}}
child {node {} child {node {}}}
child {node {} child {node {}}};
\end{tikzpicture}
```

![image](https://user-images.githubusercontent.com/1303842/99194394-609a8000-277f-11eb-8b0f-8b8702477d9a.png)

Alternatively you can start using the excellent package [`forest`](https://www.ctan.org/pkg/forest) to manipulate multiple trees and many other goodies about them.

**Comment by hmenke** [comment]
As Ilhan explained this is actually the expected behavior because node options are always inherited to nested scopes.  This might be annoying in this case but the reverse is annoying in other cases.  Also I try to keep the impact on existing behavior minimal so I'm not going to attempt to fix this. Please use one of the many alternatives that have been proposed.
