### ISSUE TITLE
The function dim that returns the dimension of an array appears to be undocumented

### ISSUE THREAD

**Issue by eg9** [pgf-tikz/pgf#964]
Version: 3.1.7a

The function `dim` is defined in lines 269–278 of `pgfmathfunctions.misc.code.tex`, but there is no trace of it in the manual. It should be described in section 94.3.8 Miscellaneous functions.

**Comment by marmotghost** [comment]
You have been explicitly informed that this function does not quite work properly. Now you try to go this route: post an issue here, get a repaired version at some point, and then pretend that you posted your examples on TeX.SE in good faith. Just to repeat my example that you certainly came across and now seem to have "forgotten".
```
\documentclass{article}
\usepackage{tikz}
\begin{document}
\def\lstA{1,2,3,4}
\pgfmathtruncatemacro{\dimA}{dim(\lstA)}\dimA

\def\lstB{1.2,2.2,3.2,4.2}
\pgfmathtruncatemacro{\dimB}{dim(\lstB)}\dimB
\end{document}
```
gives `4` and `6` (and again, you were *told* that this is the case). Of course, it is possible to define properly working `dim` functions. How do I know? Because I posted some on some Q & A sites.

**Comment by eg9** [comment]
@marmotghost 

If I properly use an array as the manual states, I get 4 in both cases.

```
\documentclass{article}
\usepackage{tikz}
\begin{document}
\def\lstA{1,2,3,4}
\pgfmathsetmacro{\dimA}{dim({\lstA})}\dimA
\def\lstAA{{1,2,3,4}}
\pgfmathsetmacro{\dimAA}{dim(\lstA)}\dimAA

\def\lstB{1.2,2.2,3.2,4.2}
\pgfmathtruncatemacro{\dimB}{dim({\lstB})}\dimB
\def\lstBB{{1.2,2.2,3.2,4.2}}
\pgfmathtruncatemacro{\dimBB}{dim(\lstBB)}\dimBB

\end{document}
```

**Comment by muzimuzhi** [comment]
Mentioned code lines
https://github.com/pgf-tikz/pgf/blob/88f5a0efce527de4af0c28f829dcb33411e98563/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex#L269-L278

Following @marmotghost's suggestion, I found a `dim` problem from [this comment in TeX.SX](https://tex.stackexchange.com/questions/35938/how-to-find-the-length-of-a-pgf-array/35949#comment449328_35949), which said `dim` function returns wrong answer when the array has only one element.

```tex
\documentclass{article}
\usepackage{tikz}

\begin{document}
\def\lstC{{10}}
\pgfmathtruncatemacro{\dimC}{dim({10})}\dimC % expected 1, got 2, the number of tokens in "10"
\end{document}
```

**Comment by marmotghost** [comment]
@muzimuzhi There are more problems. It is just hilarious how eg9 tries to defend the fact that he uses the function despite having heard about complications. We can now play another game in which for every case in which it does not work we find a workaround. BTW, what does it mean "If I properly use an array as the manual states", didn't this person just open an issue because it is *not* explained in the manual?

**Comment by hmenke** [comment]
@muzimuzhi `dim({10})` is just the good old brace stripping problem.

Everyone else, please resolve your disputes elsewhere.

**Comment by ilayn** [comment]
Well, well nice to see old faces :) 

@marmotghost You might want to cool down a bit. Passive aggression in open source software is demonstrably fruitless. Try maintaining some python packages it's so much fun.

@eg9 This function is there since the dawn of time and I am pretty sure Mark and Till looked at this more than once if I remember correctly. My understanding is in TikZ codebase not every piece of code is meant to appear in the documentation. Some of them are for internal use some of them are experimental with varying degree of robustness lingers for a while either disappears or becomes official.

**Comment by ilayn** [comment]
In fact the reason I remember this because of my old comment; I was trying to get this array business going in TikZ. 

https://tex.stackexchange.com/questions/283081/is-there-a-way-to-automatically-transpose-a-matrix-written-in-latex#comment682682_283094

**Comment by marmotghost** [comment]
@ilayn  It would not be so frustrating if this person would have mentioned that he had been explicitly informed that it does not work, and that it had been suggested to him that this is the reason why it is not documented. Now he comes here and pretends that the creators and maintainers of pgf had just forgotten to put it in the manual, and it needed his great wisdom to fix this. I find that outrageous, sorry. At the very least he could have mentioned that the existence of the command as well as its limitations were communicated to him in a chat.

**Comment by ilayn** [comment]
@marmotghost It doesn't matter. This is internet people are different. You can't expect everyone comply with your version of correct behavior.

**Comment by eg9** [comment]
@ilayn I simply forgot about the issue with length one arrays. In my experiments, the function works correctly (when the correct syntax for arrays is used, that is, with additional braces).

This should be fixed upstream, because extracting the length of an array is _obviously_ a needed feature.

**Comment by marmotghost** [comment]
@ilayn  Well, but to point out that there is an issue with the manual if you have been informed that the omission is most likely deliberate, is this how we are to behave in the internet? Just ignore the context and everything and just open an issue to steal even more time from those who keep the manual up-to-date, instead of, as one could expect from a L3 team member, finally clean up the L3 documentation so that others can also read and use it?

**Comment by ilayn** [comment]
@marmotghost As a person who has been chastised countless times as a maintainer please humor me. Try not reacting to this issue for a full day; set up an alarm watch people comment disagreeing with you and resist the temptation. I am asking as a favor and hopefully to demonstrate that it helps a lot to take a break. Tomorrow if you feel the same, come with all guns-ablazing again and I will personally implement this goddamn dim function. Now please allow me comment on the dim issue.

@eg9 There are multiple issues with this array stuff. One of them is the content of the array and the array syntax itself. It is extremely delicate and if my memory serves me right if they could they would have removed it. The brace business as Henri mentioned is an annoyance. The other part is usage; since TeX is what it is providing next to nothing as data structures it is just a terrible mess of braces, no linked lists, nothing. Hence after a couple of hours you realize that this is the wrong language to do array operations. Maybe Lua would help or maybe L3 has amazing new tech that can handle this but imagine you have a ragged array meaning that first row has 3 elements and next row has 4 due to user error. There is simply no point in pursuing additional features of such fragile machinery and my personal speculation is that it is this reason they stopped doing anything about arrays in TikZ math stuff. Because you don't have a memory allocation for an array. You are simply bookkeeping the braces. Should we expand the elements, should we count unexpanded, what happens if unexpanded items expand to new elements etc. etc.

For the dim stuff the easiest fix is to implement a simple for loop and a counter and stop when you are done and print the number for a 1D array. Anything else is basically an invitation to countless bugs and edge cases.

**Comment by eg9** [comment]
@hmenke I have no dispute with anybody here. I'm expecting that irrelevant messages are cleaned up.
